
# Calculate odometry
odometry:
  wheels_base: 1.1
  frame_id: odom
  child_frame_id: base_link
  direction_zero: 392

# Convert pulse to velocity
tachometer:
  calibrate_max_rpm_motor: 1654
  calibrate_max_velocity: 22
  wheels_diameter: 0.53
  kalman_q_noise: 0.0007
  kalman_r_noise: 0.001