PumaDwaLocalPlanner:
  topic_odom: puma/odometry/filtered

  max_velocity: 1.3
  min_velocity: 0.3 # Tambien es la velocidad lineal de giro
  max_steering_angle: 0.785 # 45 grados 
  acceleration_x: 0.2
  desacceleration_x: 0.3
  distance_for_desacceleration: 4.0

  reverse_limit_distance: 2.0
  time_simulation: 4.0

  xy_goal_tolerance: 0.5
  steering_samples: 12

  factor_cost_deviation_: 15.0
  factor_cost_distance_goal: 4.0
  factor_cost_angle_to_plan: 13.0
  factor_cost_obstacle: 5.0