# footprint: [[-1.6, -0.65], [-1.6, 0.65], [0.4, 0.65], [0.4, -0.65]]
# footprint: [[-0.9, -0.65], [-0.9, 0.65], [1, 0.65], [1, -0.65]]
footprint: [[-0.4, -0.65], [-0.4, 0.65], [1.6, 0.65], [1.6, -0.65]]

obstacle_range: 10
raytrace_range: 12

obstacle_layer:
  footprint_clearing_enabled: true
  observation_sources: camera_front_sensor camera_rear_sensor
  camera_front_sensor: {
    sensor_frame: camera_front_depth_frame,
    data_type: PointCloud2,
    topic: /puma/sensors/camera_front/depth/color/points,
    marking: true,
    clearing: true,
    min_obstacle_height: 0.6,
    max_obstacle_height: 4.0,
  }
  camera_rear_sensor: {
    sensor_frame: camera_rear_depth_optical_frame,
    data_type: PointCloud2,
    topic: /puma/sensors/camera_rear/depth/color/points,
    marking: true,
    clearing: true,
    min_obstacle_height: 1.0,
    max_obstacle_height: 1.6,
  }
  enabled: true
  track_unknown_space: true
  combination_method: 1
  lethal_cost_threshold: 100
  origin_z: 0.0
  z_resolution: 0.2
  z_voxels: 10
  mark_threshold: 0
  publish_voxel_map: true
