local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  rolling_window: true
  width: 13.0
  height: 13.0
  resolution: 0.3
  transform_tolerance: 0.5

  inflation_layer:
    enabled: true
    cost_scaling_factor: 2.0 # exponential rate at which the obstacle cost drops off (default: 10)
    inflation_radius: 2.0 # max. distance from an obstacle at which costs are incurred for planning paths.

  plugins:
    - { name: obstacle_layer, type: "costmap_2d::VoxelLayer" }
    - { name: inflation_layer,  type: "costmap_2d::InflationLayer"}
