
footprint: [[-1.6, -0.65], [-1.6, 0.65], [0.4, 0.65], [0.4, -0.65]]
transform_tolerance: 0.2
map_type: costmap

obstacle_range: 10
raytrace_range: 12

obstacle_layer:
  footprint_clearing_enabled: true
  inflation_radius: 2
  observation_sources: camera_sensor
  camera_sensor: {sensor_frame: camera_depth_optical_frame, 
                  data_type: PointCloud2, 
                  topic: /puma/camera/depth/color/points, 
                  marking: true, 
                  clearing: true,
                  min_obstacle_height: 0.2}
  enabled: true
  track_unknown_space: false
  combination_method: 1
  lethal_cost_threshold: 100


inflation_layer:
  enabled:              true
  cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.5  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
  map_topic:            "/map"


# observation_sources: laser_camera
# laser_camera: {sensor_frame: camera_link, data_type: LaserScan, topic: /camera/scan, marking: true, clearing: true}