puma_controller:
  accelerator_topic: puma/accelerator/command
  brake_topic: puma/brake/command
  reverse_topic: puma/reverse/command
  ackermann_topic: puma/control/ackermann/command
  direction_topic: puma/direction/command
  max_value_brake: 1000
  min_value_brake: 0

ackermann_converter:
  cmd_vel_topic: cmd_vel
  wheel_base: 1.15
  ackermann_topic: puma/control/ackermann/command
  arduino_status_topic: puma/arduino/status