puma_controller:
  range_accel_converter: [23, 100]
  connect_to_ackermann_converter: false
  limit_angle_degree: 45

ackermann_converter:
  cmd_vel_topic: cmd_vel
  wheel_base: 1.15
  ackermann_topic: puma/control/ackermann/command
  arduino_status_topic: puma/arduino/status
