amcl:
  use_map_topic: true
  base_frame_id: camera_link
  odom_frame_id: odom
  scan_topic: /camera/scan
  update_min_d: 0.1
  update_min_a: 0.2
  kld_err: 0.05
  kld_z: 0.99
  transform_tolerance: 0.5
  resample_interval: 1
  laser_lambda_short: 0.1
  laser_model_type: likelihood_field
  min_particles: 500
  max_particles: 2000
  alpha1: 0.2
  alpha2: 0.2
  alpha3: 0.2
  alpha4: 0.2
  alpha5: 0.1
  odom_model_type: diff
  gui_publish_rate: 10.0
  save_pose_rate: 0.5