DWAPlannerROS:
  max_vel_theta: 1.0
  max_vel_trans: 3
  max_vel_x: 1.5
  max_vel_y: 0.0

  min_vel_theta: 0.4
  min_vel_trans: 0.1
  min_vel_x: 0.3
  min_vel_y: 0

  acc_lim_theta: 3.2
  acc_lim_trans: 2
  acc_lim_x: 0.7
  acc_lim_y: 0
  sim_time: 1.5
  vx_samples: 5
  vy_samples: 0
  vth_samples: 10

  prune_plan: false
  theta_stopped_vel: 0

  latch_xy_goal_tolerance: false
  yaw_goal_tolerance: 1.5
  xy_goal_tolerance: 1.0
