global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 1.0
  # static_map: false                # Desactiva el mapa estático para usar el mapa de RTAB-Map
  rolling_window: true            # No usar rolling window en el costmap global (depende de tus necesidades)
  resolution: 0.05                 # Ajusta la resolución según tu precisión deseada
  transform_tolerance: 0.5
  width: 25.0
  height: 25.0

  map_topic: "/map"
  inflation_layer:
    enabled: true
    cost_scaling_factor: 2.0 # exponential rate at which the obstacle cost drops off (default: 10)
    inflation_radius: 4 # max. distance from an obstacle at which costs are incurred for planning paths.

  transform_tolerance: 0.5
  plugins:
  
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
    - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer" }
