global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 0.2
  static_map: false                # Desactiva el mapa estático para usar el mapa de RTAB-Map
  rolling_window: false            # No usar rolling window en el costmap global (depende de tus necesidades)
  resolution: 0.05                 # Ajusta la resolución según tu precisión deseada
  transform_tolerance: 0.5
  map_topic: "/map"

  transform_tolerance: 0.5
  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
    - { name: obstacle_layer, type: "costmap_2d::ObstacleLayer" }

 