global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 3.0
  publish_frequency: 2.0
  rolling_window: true            # No usar rolling window en el costmap global (depende de tus necesidades)
  resolution: 0.5                 # Ajusta la resolución según tu precisión deseada
  transform_tolerance: 0.5
  width: 40
  height: 40

  inflation_layer:
    enabled: true
    cost_scaling_factor: 10.0 # exponential rate at which the obstacle cost drops off (default: 10)
    inflation_radius: 4 # max. distance from an obstacle at which costs are incurred for planning paths.


  transform_tolerance: 0.5
  plugins:
    - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer" }
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
