PumaHybridAStarPlanner:
  # busqueda de celdas
  step_size_meters: 0.3
  division_theta: 3
  theta_limit: 0.228 # (equivalente a M_PI / 5)
  xy_goal_tolerance: 0.4

  # factor para costes
  factor_cost_distance: 10
  factor_cost_angle_curve: 4
  factor_cost_angle_goal: 10
  factor_cost_obstacle: 100
  factor_cost_unknown: 0.4

  # Suavizado en curvas de dubin
  enable_dubin: false
  division_curve: 6