PumaHybridAStarPlanner:
  # busqueda de celdas
  step_size_meters: 0.3
  division_theta_: 3
  theta_limit: 0.228 # (equivalente a M_PI / 5)

  # factor para costes
  factor_cost_distance: 10
  factor_cost_angle_curve: 6
  factor_cost_angle_goal: 10
  factor_cost_obstacle: 100

  # Suavizado en curvas de dubin
  enable_dubin: true
  division_curve: 6