local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 10.0
  height: 10.0
  resolution: 0.05
  transform_tolerance: 0.5

  inflation_layer:
    enabled: true
    cost_scaling_factor: 2.0 # exponential rate at which the obstacle cost drops off (default: 10)
    inflation_radius: 2 # max. distance from an obstacle at which costs are incurred for planning paths.
    
  plugins:
    - { name: obstacle_layer, type: "costmap_2d::ObstacleLayer" }
    - { name: inflation_layer, type: "costmap_2d::InflationLayer" } # Capa de inflación para evitar obstáculos

