PumaDwaLocalPlanner:
  topic_odom: puma/odometry/filtered

  max_velocity: 1.0
  min_velocity: 0.3
  max_steering_angle: 0.76
  acceleration_x: 0.2
  desacceleration_x: 0.3
  distance_for_desacceleration: 4.0

  reverse_limit_distance: 3.0
  time_simulation: 4.0
  min_turn_radius: 2.25 

  xy_goal_tolerance: 0.5
  steering_samples: 7
  velocity_samples: 1

  factor_cost_deviation_: 2.0
  factor_cost_distance_goal: 12.0