# footprint: [[-1.6, -0.65], [-1.6, 0.65], [0.4, 0.65], [0.4, -0.65]]
footprint: [[-0.9, -0.65], [-0.9, 0.65], [1, 0.65], [1, -0.65]]
transform_tolerance: 0.2
map_type: costmap

obstacle_range: 10
raytrace_range: 12

obstacle_layer:
  footprint_clearing_enabled: true
  observation_sources: camera_front_sensor camera_rear_sensor
  camera_front_sensor:
    {
      sensor_frame: camera_front_depth_frame,
      data_type: PointCloud2,
      topic: /puma/sensors/camera_front/depth/color/points,
      marking: true,
      clearing: true,
      min_obstacle_height: 0.6,
      max_obstacle_height: 4.0,
    }
  camera_rear_sensor: {
    sensor_frame: camera_rear_depth_optical_frame,
    data_type: PointCloud2,
    topic: /puma/sensors/camera_rear/depth/color/points,
    marking: true,
    clearing: true,
    min_obstacle_height: 0.8,
  }
  enabled: true
  track_unknown_space: true
  combination_method: 1
  lethal_cost_threshold: 100rtabmap_odom

inflation_layer:
  enabled: true
  cost_scaling_factor: 3.0 # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius: 0 # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled: true
  map_topic: "/map"
# observation_sources: laser_camera
# laser_camera: {sensor_frame: camera_link, data_type: LaserScan, topic: /camera/scan, marking: true, clearing: true}
