global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 0.5
  static_map: true
  rolling_window: false

  obstacle_layer:
    footprint_clearing_enabled: true
    inflation_radius: 2
    observation_sources: camera_front_sensor
    camera_front_sensor:
      {
        sensor_frame: camera_depth_optical_frame,
        data_type: PointCloud2,
        topic: /puma/sensors/camera_front/depth/color/points,
        marking: true,
        clearing: true,
        min_obstacle_height: 0.3,
      }
    enabled: true
    track_unknown_space: false
    combination_method: 1
    lethal_cost_threshold: 100

  transform_tolerance: 0.5
  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}

 