local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 15.0
  height: 15.0
  resolution: 0.05
  transform_tolerance: 0.5

  obstacle_layer:
    footprint_clearing_enabled: true
    inflation_radius: 2
    observation_sources: camera_front_sensor camera_rear_sensor
    camera_front_sensor:
      {
        sensor_frame: camera_front_depth_optical_frame,
        data_type: PointCloud2,
        topic: /puma/sensors/camera_front/depth/color/points,
        marking: true,
        clearing: true,
        min_obstacle_height: 0.2,
      }
    camera_rear_sensor: {
      sensor_frame: camera_rear_depth_optical_frame,
      data_type: PointCloud2,
      topic: /puma/sensors/camera_rear/depth/color/points,
      marking: true,
      clearing: true,
      min_obstacle_height: 0.2,
    }
    enabled: true
    track_unknown_space: false
    combination_method: 1
    lethal_cost_threshold: 100

  plugins:
    - { name: static_layer, type: "costmap_2d::StaticLayer" }
    - { name: obstacle_layer, type: "costmap_2d::ObstacleLayer" }
