switch_topic_a: "/puma/brake/switch_a"
switch_topic_b: "/puma/brake/switch_b"

topic_brake_front: "/puma/brake/front_wheels"
topic_brake_rear: "/puma/brake/rear_wheels"

extra_steps_front: 200
extra_steps_rear: 200
