
#PUBLISH ALL JOINT STATES
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

# Velocity controller
wheel_right_controller:
  type: velocity_controllers/JointVelocityController
  joint: wheel_right_back_joint

wheel_left_controller:  
  type: velocity_controllers/JointVelocityController
  joint: wheel_left_back_joint

# Position controller
dir_right_controller: 
  type: position_controllers/JointPositionController
  joint: dir_right_joint

dir_left_controller: 
  type: position_controllers/JointPositionController
  joint: dir_left_joint



